###################
## General Stuff ##
###################
# Below is the error message to display when someone who does have permission tries to use a command
# From this plugin.
noPermMessage: "&e&l(!) &3You do not have permission to perform this command!"

# Custom Join Message, Keep CustomJoin at true to enabled custom join message
# Set it to false to disabled it.
CustomJoin: true
# If above is false the below will not show on the server.
hasPlayedMessage: "&eWelcome Back, &e%PLAYERNAME%"
newPlayerMessage: "&eWelcome to Factions, &e%PLAYERNAME%"

# Custom Quit Message, Keep CustomLeave at true to enabled custom quit message
# Set it to false to disabled it.
CustomLeave: true
# If above is false the quit message will not show on the server.
playerQuitMessage: "%PLAYERNAME%, has left the server."

# TNT Events, They can both be false, to let you just place tnt as a block. and then light it up
# The Vanilla Way flint 'n' steel etc. Or Set one to true and the other false
# Example: You want to have TNT explode when placed straight away:
# autoExplode: true
# rightclickExplode: false
# Example: You want to have TNT explode when right clicked:
# autoExplode: false
# rightclickExplode: true
# if you have them both set to true nothing will happen block will just place normally.
rightclickExplode: true
autoExplode: true



